### ISSUE TITLE
On large number of load directives, begins dropping blocks

### ISSUE THREAD

**Issue by Wideshanks** [jostylr/literate-programming#15] opened 2015-02-05 04:03 UTC
If I do a large number of loads, it will begin to drop some of the blocks, so I'll end up with a raw _"Blockname" in my output file.

Which load gets dropped is somewhat random. Recompiling in a loop and checking the single output file:

```
$ for i in `seq 1 25`; do literate-programming --verbose lit/README.md && sha1sum src/main.c; done;
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
309d399faaa16b7171eab16c6be58a9a36db1d3a  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
df2578a11c628dea68a682f275ad6a38cd3b7bff  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
f6b2ed0fec8c7b582f0c6c1614f3a7d006d3a195  src/main.c
c8b8aa54aeda20a5fbd14ca420a7ba47279ecbe5  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
f6b2ed0fec8c7b582f0c6c1614f3a7d006d3a195  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
c8b8aa54aeda20a5fbd14ca420a7ba47279ecbe5  src/main.c
56da6dd05138c11ea057b7d7d20738239c1c6260  src/main.c
c8b8aa54aeda20a5fbd14ca420a7ba47279ecbe5  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
309d399faaa16b7171eab16c6be58a9a36db1d3a  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
c8b8aa54aeda20a5fbd14ca420a7ba47279ecbe5  src/main.c
309d399faaa16b7171eab16c6be58a9a36db1d3a  src/main.c
110fce221bab37bed2d415e30a9949eba24bac4f  src/main.c
```

Here are the [7 loads in question](https://raw.githubusercontent.com/Wideshanks/5mc/gh-pages/lit/README.md):

```
[altitude](# "load:lit/altitude.md")

[mission](# "load:lit/mission.md")

[crew](# "load:lit/crew.md")

[bomber](# "load:lit/bomber.md")

[input](# "load:lit/input.md")

[setup](# "load:lit/setup.md")

[main](# "load:lit/main.md").
```

Here are some outputs, with sha1s, and it seems easier to show the compile errors rather than the source to see what blocks aren't being rendered:

https://gist.github.com/Wideshanks/7a842523bda66c3f4157

Out of running that one-liner above in [250 trials](https://gist.github.com/Wideshanks/346ce62837bf2ad0c2e5), there were 17 unique outputs. These are the most common outputs and the files they're losing:

1. `4bac4f`, with `mission.md` dropping.
2. `9ecbe5` `altitude.md`
3. `1c6260` `input.md`

The lp.md mentions that these loads are done asynchronously. Could something be wrong with ensuring all the loads finish before compilation?

**Comment by jostylr** [comment] 2015-02-06 07:52
The problem was that the loaded files were not waiting to compile. Now they will. This is a hard problem to definitively test for, but I did manage to replicate your problem with some timeouts and now the problem is fixed in my trials. Check to see if 0.8.4 works for you. 

I think I had in my mind that if loaded files called other loaded files, then they would also have load directives. Of course, that's wasteful and this fixes it.

Also, I am working on a different core for this which should make async stuff stronger and more robust; see [literate-programming lib](https://github.com/jostylr/literate-programming-lib)  for progress.

**Closed by jostylr** 2015-02-06 07:52 UTC

**Comment by Wideshanks** [comment] 2015-02-07 03:46
Thanks, it works.
